#베이스 이미지 설정
FROM node:latest AS build
#작업 디렉토리 설정
WORKDIR /meetz-front/
#의존성 설치
COPY package*.json ./
RUN npm install
#앱 소스 복사
COPY . .
# .env 파일 생성
RUN echo "VITE_NOW_BASEURL=deployed\n\
VITE_API_LOCAL_URL=http://localhost:8088\n\
VITE_API_DEPLOYED_URL=http://i11c108.p.ssafy.io:8088" > .env
#포트번호
EXPOSE 3000
#빌드
RUN npm run build
#서버 실행
CMD ["npm","run","dev"]
